// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH0xeHQZsZUTtdv2kukd0BOI8Quomkuqw',
    appId: '1:497512590176:android:85d2d51778de98dd960c05',
    messagingSenderId: '497512590176',
    projectId: 'isportistan',
    storageBucket: 'isportistan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB94dUYY9pXBlkTPbE69bdXfJ32i1z8dS4',
    appId: '1:497512590176:ios:4ce8318dbd2fe6d0960c05',
    messagingSenderId: '497512590176',
    projectId: 'isportistan',
    storageBucket: 'isportistan.appspot.com',
    androidClientId: '497512590176-114b5bpiq5u8ffuvac5q216vvoniqhtk.apps.googleusercontent.com',
    iosClientId: '497512590176-h2v0qkgkp4bj4aodu56u8mnrgknd39cr.apps.googleusercontent.com',
    iosBundleId: 'co.in.sportistan.sportistan',
  );
}