// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe9kYHNw7oRj6FzAVD3TD4G3AJVxmzXc4',
    appId: '1:618630025990:android:bddf0c8112b1c168394487',
    messagingSenderId: '618630025990',
    projectId: 'sportistanpro',
    storageBucket: 'sportistanpro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNw8Dm3ffwuVD75m3NUriEaQhHbE6066g',
    appId: '1:618630025990:ios:da43b20a829702bc394487',
    messagingSenderId: '618630025990',
    projectId: 'sportistanpro',
    storageBucket: 'sportistanpro.appspot.com',
    androidClientId: '618630025990-lbtq65ih7vbna96aapnfcqr3m7nh5ub2.apps.googleusercontent.com',
    iosClientId: '618630025990-0gbkdso12bnmdqfedp2p1qt7lsfcnh1f.apps.googleusercontent.com',
    iosBundleId: 'co.in.sportistan.sportistan',
  );
}
